version: "3.9"

services:
  urlshortener:
    container_name: urlshortener
    build: ./
    command: ["./wait-for-it.sh", "postgres:5432", "--timeout=5", "--", "./urlShortener"]
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=urlshorten
    ports:
      - "5432:5432"
    volumes:
      - ./internal/db/postgres/migration/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./internal/db/postgres/data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
