  on:
    push:
      branches: [ "main" ]
      pull_request:
        branches: [ "main" ]
  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21'

        - name: lint
          run: make lint
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21'

        - name: test
          run: make test
    coverage:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21'

        - name: install goveralls
          run: go install github.com/mattn/goveralls@latest

        - name: test
          run: make test

        - name: send coverage
          run: goveralls -coverprofile=$GITHUB_WORKSPACE/.coverage.out -service=github
          env:
            COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    build:
      runs-on: ubuntu-latest
      needs: [ lint, test ]
      steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: 1.21

        - name: build
          run: make build